//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public address()
        {
            this.orders = new HashSet<orders>();
            this.invoices = new HashSet<invoices>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int country_id { get; set; }
        public int city_id { get; set; }
        public int town_id { get; set; }
        public int district_id { get; set; }
        public string postal_code { get; set; }
        public string address_text { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual countries countries { get; set; }
        public virtual districts districts { get; set; }
        public virtual towns towns { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoices> invoices { get; set; }
    }
}
