//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class images_paths
    {
        public string image_id { get; set; }
        public string name { get; set; }
        public string image_url { get; set; }
        public Nullable<System.DateTime> date_of_creation { get; set; }
        public int item_id { get; set; }
    
        public virtual items items { get; set; }
    }
}
