//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETRADE4Entities : DbContext
    {
        public ETRADE4Entities()
            : base("name=ETRADE4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<category1> category1 { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<districts> districts { get; set; }
        public virtual DbSet<images_paths> images_paths { get; set; }
        public virtual DbSet<invoice_details> invoice_details { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<towns> towns { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
